import path from "path";
import fs from "fs";
import { getDirectoriesRecursive } from "./utils.js";
import { createMisconfigurationFiles, extractMisconfigurations } from "./misconfigurationHandler.js";
import { extractVulnerabilities, createVulnerabilityFiles } from "./vulnerabilityHandler.js";
import { outDir, indexFileTemplate } from "./consts.js";

/*
The json structure, generated by the trivy report can be found at the bottom of this file:
*/
await main();

async function main() {
  const trivyJsonReport = JSON.parse(await fs.promises.readFile("./src/data/report.json"));

  const vulnerabilities = extractVulnerabilities(trivyJsonReport);
  const misconfigurations = extractMisconfigurations(trivyJsonReport);

  await createVulnerabilityFiles(vulnerabilities);
  await createMisconfigurationFiles(misconfigurations);

  await createIndexFiles();
}

// Each directory needs its own index file
async function createIndexFiles() {
  const dirs = getDirectoriesRecursive(outDir);
  const indexTemplate = (await fs.promises.readFile(indexFileTemplate)).toString();

  dirs.forEach((dir) => {
    const pathElements = dir.split(path.sep);
    const title = pathElements[pathElements.length - 1];
    // Top level index file has special title
    if (title.includes("out")) {
      fs.writeFileSync(dir + "/" + "_index.md", indexTemplate.replace("_title", "Vulnerability Scan"));
    } else {
      fs.writeFileSync(dir + "/" + "_index.md", indexTemplate.replace("_title", title));
    }
  });
}

/*
{
  "ClusterName": "string",
  "Misconfigurations": [
    {
      "Kind": "string",
      "Namespace": "string",
      "Name": "string",
      "Results": [
        {
          "Class": "string",
          "Target": "string",
          "Type": "string",
          "MisconfSummary": {
            "Successes": "integer",
            "Failures": "integer",
            "Exceptions": "integer"
          },
          "Misconfigurations": [
            {
              "Type": "string",
              "ID": "string",
              "AVDID": "string",
              "Title": "string",
              "Description": "string",
              "Message": "string",
              "Namespace": "string",
              "Query": "string",
              "Resolution": "string",
              "Severity": "string",
              "PrimaryURL": "string",
              "References": [
                "string"
              ],
              "Status": "string",
              "CauseMetadata": {
                "Provider": "string",
                "Service": "string",
                "StartLine": "integer",
                "EndLine": "integer",
                "Code": {
                  "Lines": [
                    {
                      "Number": "integer",
                      "Content": "string",
                      "IsCause": "boolean",
                      "Annotation": "string",
                      "Truncated": "boolean",
                      "FirstCause": "boolean",
                      "LastCause": "boolean"
                    }
                  ]
                }
              }
            }
          ]
        }
      ]
    }
  ],
  "Vulnerabilities": [
    {
      "Kind": "string",
      "Namespace": "string",
      "Name": "string",
      "Results": [
        {
          "Class": "string",
          "Target": "string",
          "Type": "string",
          "Vulnerabilities": [
            {
              "VulnerabilityID": "string",
              "VendorIDs": [
                "string"
              ],
              "PkgName": "string",
              "InstalledVersion": "string",
              "FixedVersion": "string",
              "Layer": {
                "Digest": "string",
                "DiffID": "string"
              },
              "DataSource": {
                "ID": "string",
                "Name": "string",
                "URL": "string"
              },
              "Title": "string",
              "Severity": "string"
            }
          ]
        }
      ]
    }
  ]
}
*/
